spring:
  datasource:
    url: jdbc:h2:file:~/.finance/db
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-ui

server:
  servlet:
    context-path: /api
  port: 3001
